### ISSUE TITLE
Code use question (license)

### ISSUE THREAD

**Issue by colehurwitz** [lyprince/hierarchical_lfads#9]
This is a really cool project! I was hoping to simulate some data for a related (but different) project using your codebase. However, I didn't want to reuse your data simulation code since there is no open-source license for the repository. Are you planning on adding a license for this project? 

Best, Cole

**Comment by lyprince** [comment]
Hi Cole,

Sorry for leaving this so late! I've added an MIT Licence. Hopefully, this hasn't significantly impeded progress in your project.

Luke
